name: Sandbox

on:
  pull_request_review:
    types:
      - submitted
    branches-ignore:
      - main

## env      

jobs:
  Plan:
    name: "Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: message
        run: echo "staging development Plan"

  Apply:
    # Running a workflow when a pull request is approved
    # in this case, it will run on staging development
    if: github.event.review.state == 'approved'
    name: "Apply"
    runs-on: ubuntu-latest
    needs: [Plan]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: message
        run: echo "staging development only PR is approved"
