name: Production

## This template is to run exclusively in production environment

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
  pull_request_review:
    types:
      - submitted

## env

jobs:
  Plan:
    name: "Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: message
        run: echo "Production development when PR is closed or pull_request_review are submitted"
  
  terragrunt-apply:
    # Running a workflow when a pull request is closed and merged
    # in this case, it will run on production development
    if: github.event.pull_request.merged == true
    name: "Apply"
    needs: [Plan]

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: message
        run: echo "Production development when PR request is closed and merged"