name: Production Pipeline > Apply

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - master

jobs:
  terragrunt-plan:
    name: "Apply Pipeline | Production"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terragrunt PRD Apply
        run: echo "terragrunt run-all apply --terragrunt-non-interactive > Apply Pipeline | Production"
