name: Production Pipeline > Apply

on:
  pull_request:
    types:
      - closed

  push:
    branches:
      - master

jobs:
  terragrunt-plan:
    if: github.event.pull_request.merged == true
    name: "Apply Pipeline | Production"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terragrunt PRD Apply
        run: echo "apenas merged > Apply Pipeline | Production"
