name: Production Merged

on:
  pull_request:
    types:
      - closed

  # push:
  #   branches:
  #     - master

jobs:
  terragrunt-plan:
    if: github.event.pull_request.merged == true
    name: "Apply"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terragrunt PRD Apply
        run: echo "apenas merged > tf-apply-prd.yml"
