name: Production Pipeline

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches:
      - master
  pull_request_review:
      types:
        - submitted

jobs:
  terragrunt-plan:
    name: "Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terragrunt PRD Plan
        run: echo "Plan tf-plan-prd.yml"
